name: CI

on:
  push:
    # branches:

  # - main
  pull_request:
     # branches:
      # - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test  

      - name: Dependency Vulnerability Scan
        run: npm audit --audit-level=high 
      
      - name: Secret Scan 
        uses: trufflesecurity/trufflehog@main


      - name: Build Docker image
        run: docker build -t devsec-api . 

